public with sharing class CustomMenuController {

    public PageReference newCustomer() {
        return null;
    }


    public PageReference closeCustomerAccount() {
        return null;
    }


    public PageReference customerPlan() {
        return null;
    }


    public PageReference changeCustomerThing() {
        return null;
    }


    public PageReference addThingToCustomer() {
        return null;
    }

}