public class ThingParkCreateSubscriberJson {
    // Subscriber
    //    id (string, optional): Id of the subscriber. ,
    //    ref (string, optional): Ref of the subscriber. ,
    //    vendorRef (string, optional): Ref of the vendor in relation with the subscriber. ,
    //    name (string, optional): Name of the subscriber. ,
    //    contactEmail (string, optional): Email of the subscriber contact. ,
    //    contactInfo (string, optional): Information about the subscriber contact. ,
    //    organization (string, optional): Organization of the subscriber. ,
    //    externalId (string, optional): Third-party identifier of the subscriber. ,
    //    defaultISMBandIds (Array[string], optional): List of ids of the default ISM bands for the subscriber. ,
    //    primaryUser (User, optional): First user account created for the subscriber. Only returned upon subscriber creation.
}